package de.saring.sportstracker.gui.dialogs;

import javax.swing.ActionMap;
import javax.swing.JDialog;
import javax.swing.JTextField;

import org.jdesktop.application.Action;

import com.google.inject.Inject;

import de.saring.sportstracker.gui.STContext;
import de.saring.util.gui.DialogUtils;

/**
 * This is the "About" dialog of the SportsTracker application.
 * @author  Stefan Saring
 * @version 1.0
 */
public class AboutDialog extends JDialog {

    /** Constants for action and property names. */
    private static final String ACTION_CLOSE = "st.dlg.about.close";
    
    /** 
     * Creates a new AboutDialog.
     * @param context the SportsTracker context
     */
    @Inject
    public AboutDialog (STContext context) {
        super (context.getMainFrame (), true);
        initComponents ();
        this.getRootPane ().setDefaultButton (btClose);
        
        tpAuthors.setTitleAt (0, context.getResReader ().getString ("st.dlg.about.title.authors"));
        tpAuthors.setTitleAt (1, context.getResReader ().getString ("st.dlg.about.title.translators"));

        // use same font in textareas as in textfields (not default on Win32)
        JTextField tfDummy = new JTextField ();
        taAuthors.setFont (tfDummy.getFont ());
        taTranslators.setFont (tfDummy.getFont ());
        
        // setup actions
        ActionMap actionMap = context.getSAFContext ().getActionMap (getClass (), this);
        javax.swing.Action aClose = actionMap.get (ACTION_CLOSE);
        btClose.setAction(aClose);        
        DialogUtils.setDialogEscapeKeyAction(this, aClose);
    }

    /**
     * Workaround: Shows or hides this dialog. Before showing the authors and 
     * translators text areas will be scrolled to the upper left position 
     * (they are initially at the bottom otherwise).
     * @param true for show, false for hide
     */
    @Override
    public void setVisible (boolean fVisible) {
        if (fVisible) {
            taAuthors.setCaretPosition (0);
            taTranslators.setCaretPosition (0);
        }
        super.setVisible (fVisible);
    }

    /**
     * Action for closing the dialog.
     */
    @Action(name=ACTION_CLOSE)
    public void close () {
        this.dispose ();
    }
    
    /** 
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laLogo = new javax.swing.JLabel();
        laSportsTracker = new javax.swing.JLabel();
        laDescription = new javax.swing.JLabel();
        laCopyright = new javax.swing.JLabel();
        btClose = new javax.swing.JButton();
        tpAuthors = new javax.swing.JTabbedPane();
        spAuthors = new javax.swing.JScrollPane();
        taAuthors = new javax.swing.JTextArea();
        spTranslators = new javax.swing.JScrollPane();
        taTranslators = new javax.swing.JTextArea();
        separator = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setName("st.dlg.about"); // NOI18N
        setResizable(false);

        laLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/st-logo.png"))); // NOI18N
        laLogo.setName("laLogo"); // NOI18N

        laSportsTracker.setFont(laSportsTracker.getFont().deriveFont(laSportsTracker.getFont().getStyle() | java.awt.Font.BOLD));
        laSportsTracker.setText("_SportsTracker X.X.X");
        laSportsTracker.setName("st.dlg.about.sportstracker"); // NOI18N

        laDescription.setText("<html>_A tool for recording your sport activities and viewing exercise files.<br/>It's written for the Java platform.</html>"); // NOI18N
        laDescription.setName("st.dlg.about.description"); // NOI18N

        laCopyright.setText("_(C) 2007 Stefan Saring");
        laCopyright.setName("st.dlg.about.copyright"); // NOI18N

        btClose.setText("_Close");
        btClose.setName("st.dlg.about.close"); // NOI18N

        tpAuthors.setName("tpAuthors"); // NOI18N

        spAuthors.setName("spAuthors"); // NOI18N

        taAuthors.setColumns(20);
        taAuthors.setEditable(false);
        taAuthors.setRows(5);
        taAuthors.setText("_Main developer:\n\n    Stefan Saring <projects@saring.de>\n\n....\n");
        taAuthors.setName("st.dlg.about.authors"); // NOI18N
        spAuthors.setViewportView(taAuthors);

        tpAuthors.addTab("_Authors", spAuthors);

        spTranslators.setName("spTranslators"); // NOI18N

        taTranslators.setColumns(20);
        taTranslators.setEditable(false);
        taTranslators.setRows(5);
        taTranslators.setText("_German:\n    Stefan Saring <projects@saring.de>\n\n...");
        taTranslators.setName("st.dlg.about.translators"); // NOI18N
        spTranslators.setViewportView(taTranslators);

        tpAuthors.addTab("_Translators", spTranslators);

        separator.setName("separator"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(376, Short.MAX_VALUE)
                .addComponent(btClose)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpAuthors, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(laLogo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(laCopyright)
                            .addComponent(laSportsTracker)
                            .addComponent(laDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laSportsTracker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(laDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(laCopyright))
                    .addComponent(laLogo))
                .addGap(18, 18, 18)
                .addComponent(tpAuthors, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JLabel laCopyright;
    private javax.swing.JLabel laDescription;
    private javax.swing.JLabel laLogo;
    private javax.swing.JLabel laSportsTracker;
    private javax.swing.JSeparator separator;
    private javax.swing.JScrollPane spAuthors;
    private javax.swing.JScrollPane spTranslators;
    private javax.swing.JTextArea taAuthors;
    private javax.swing.JTextArea taTranslators;
    private javax.swing.JTabbedPane tpAuthors;
    // End of variables declaration//GEN-END:variables

}
