package de.saring.exerciseviewer.gui.panels;

import com.google.inject.Inject;
import de.saring.exerciseviewer.data.PVExercise;
import de.saring.exerciseviewer.gui.PVContext;
import de.saring.util.unitcalc.FormatUtils;

/**
 * This class is the implementation of the "Optional" panel, which displays all
 * the optional exercise data, such as Speed, Altitude and so on.
 *
 * @author Stefan Saring
 * @version 1.0
 */
public class OptionalPanel extends BasePanel {
    
    /**
     * Standard c'tor.
     * @param context the PolarViewer context
     */
    @Inject
    public OptionalPanel (PVContext context) {
        super (context);
        initComponents ();        
    }
    
    /** {@inheritDoc} */
    @Override
    public void displayExercise () {
        PVExercise exercise = getDocument ().getExercise ();
        FormatUtils formatUtils = getContext ().getFormatUtils ();

        // set default text for all value labels first
        laAvgSpeedValue.setText (getContext ().getResReader ().getString ("common.n_a_"));
        laMaxSpeedValue.setText (getContext ().getResReader ().getString ("common.n_a_"));
        laDistanceValue.setText (getContext ().getResReader ().getString ("common.n_a_"));
        laBikeNrValue.setText (getContext ().getResReader ().getString ("common.n_a_"));

        laAvgCadenceValue.setText (getContext ().getResReader ().getString ("common.n_a_"));
        laMaxCadenceValue.setText (getContext ().getResReader ().getString ("common.n_a_"));

        laMinAltitudeValue.setText (getContext ().getResReader ().getString ("common.n_a_"));
        laAvgAltitudeValue.setText (getContext ().getResReader ().getString ("common.n_a_"));
        laMaxAltitudeValue.setText (getContext ().getResReader ().getString ("common.n_a_"));
        laAscentValue.setText (getContext ().getResReader ().getString ("common.n_a_"));

        laMinTemperatureValue.setText (getContext ().getResReader ().getString ("common.n_a_"));
        laAvgTemperatureValue.setText (getContext ().getResReader ().getString ("common.n_a_"));
        laMaxTemperatureValue.setText (getContext ().getResReader ().getString ("common.n_a_"));
        
        // fill speed data
        if (exercise.getSpeed () != null) {
            laAvgSpeedValue.setText (formatUtils.speedToString (exercise.getSpeed ().getSpeedAVG (), 2));
            laMaxSpeedValue.setText (formatUtils.speedToString (exercise.getSpeed ().getSpeedMax (), 2));
            laDistanceValue.setText (formatUtils.distanceToString (exercise.getSpeed ().getDistance () / 1000f, 2));
            
            // bike number can't be displayed for HRM files
            if (exercise.getFileType () != PVExercise.ExerciseFileType.HRM) {
                laBikeNrValue.setText (String.valueOf (exercise.getRecordingMode ().getBikeNumber ()));
            }
        }
        
        // fill cadence data
        if (exercise.getCadence () != null) {
            laAvgCadenceValue.setText (formatUtils.cadenceToString (exercise.getCadence ().getCadenceAVG ()));
            laMaxCadenceValue.setText (formatUtils.cadenceToString (exercise.getCadence ().getCadenceMax ()));
        }
        
        // fill altitude data
        if (exercise.getAltitude () != null) {
            laMinAltitudeValue.setText (formatUtils.heightToString (exercise.getAltitude ().getAltitudeMin ()));
            laAvgAltitudeValue.setText (formatUtils.heightToString (exercise.getAltitude ().getAltitudeAVG ()));
            laMaxAltitudeValue.setText (formatUtils.heightToString (exercise.getAltitude ().getAltitudeMax ()));
            laAscentValue.setText (formatUtils.heightToString (exercise.getAltitude ().getAscent ()));
        }
        
        // fill temperature data
        if (exercise.getTemperature () != null) {
            laMinTemperatureValue.setText (formatUtils.temperatureToString (exercise.getTemperature ().getTemperatureMin ()));
            laAvgTemperatureValue.setText (formatUtils.temperatureToString (exercise.getTemperature ().getTemperatureAVG ()));
            laMaxTemperatureValue.setText (formatUtils.temperatureToString (exercise.getTemperature ().getTemperatureMax ()));
        }        
    }
        
    /** 
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLeft = new javax.swing.JPanel();
        laCadenceData = new javax.swing.JLabel();
        laBikeNr = new javax.swing.JLabel();
        laDistance = new javax.swing.JLabel();
        laMaxSpeed = new javax.swing.JLabel();
        laAvgSpeed = new javax.swing.JLabel();
        laMaxCadence = new javax.swing.JLabel();
        laAvgCadence = new javax.swing.JLabel();
        laAvgSpeedValue = new javax.swing.JLabel();
        laMaxSpeedValue = new javax.swing.JLabel();
        laDistanceValue = new javax.swing.JLabel();
        laBikeNrValue = new javax.swing.JLabel();
        laMaxCadenceValue = new javax.swing.JLabel();
        laAvgCadenceValue = new javax.swing.JLabel();
        laSpeedData = new javax.swing.JLabel();
        pRight = new javax.swing.JPanel();
        laAltitudeData = new javax.swing.JLabel();
        laMinAltitude = new javax.swing.JLabel();
        laAvgAltitude = new javax.swing.JLabel();
        laMaxAltitude = new javax.swing.JLabel();
        laAscent = new javax.swing.JLabel();
        laTemperatureData = new javax.swing.JLabel();
        laMinTemperature = new javax.swing.JLabel();
        laAvgTemperature = new javax.swing.JLabel();
        laMaxTemperature = new javax.swing.JLabel();
        laMinAltitudeValue = new javax.swing.JLabel();
        laAvgAltitudeValue = new javax.swing.JLabel();
        laMaxAltitudeValue = new javax.swing.JLabel();
        laAscentValue = new javax.swing.JLabel();
        laMinTemperatureValue = new javax.swing.JLabel();
        laAvgTemperatureValue = new javax.swing.JLabel();
        laMaxTemperatureValue = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.GridLayout(1, 2, 20, 20));

        laCadenceData.setFont(laCadenceData.getFont().deriveFont(laCadenceData.getFont().getStyle() | java.awt.Font.BOLD));
        laCadenceData.setText("_Cadence Data");
        laCadenceData.setName("pv.opt.cadence_data"); // NOI18N

        laBikeNr.setText("_Bike number:");
        laBikeNr.setName("pv.opt.bike_nr"); // NOI18N

        laDistance.setText("_Distance:");
        laDistance.setName("pv.opt.distance"); // NOI18N

        laMaxSpeed.setText("_Maximum:");
        laMaxSpeed.setName("pv.opt.maximum"); // NOI18N

        laAvgSpeed.setText("_Average:");
        laAvgSpeed.setName("pv.opt.average"); // NOI18N

        laMaxCadence.setText("_Maximum:");
        laMaxCadence.setName("pv.opt.maximum"); // NOI18N

        laAvgCadence.setText("_Average:");
        laAvgCadence.setName("pv.opt.average"); // NOI18N

        laAvgSpeedValue.setText("_n.a.");

        laMaxSpeedValue.setText("_n.a.");

        laDistanceValue.setText("_n.a.");

        laBikeNrValue.setText("_n.a.");

        laMaxCadenceValue.setText("_n.a.");

        laAvgCadenceValue.setText("_n.a.");

        laSpeedData.setFont(laSpeedData.getFont().deriveFont(laSpeedData.getFont().getStyle() | java.awt.Font.BOLD));
        laSpeedData.setText("_Speed Data");
        laSpeedData.setName("pv.opt.speed_data"); // NOI18N

        javax.swing.GroupLayout pLeftLayout = new javax.swing.GroupLayout(pLeft);
        pLeft.setLayout(pLeftLayout);
        pLeftLayout.setHorizontalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laAvgCadence)
                    .addComponent(laMaxCadence))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(pLeftLayout.createSequentialGroup()
                .addComponent(laCadenceData)
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(pLeftLayout.createSequentialGroup()
                .addComponent(laSpeedData)
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(pLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laAvgSpeed)
                    .addComponent(laMaxSpeed)
                    .addComponent(laDistance)
                    .addComponent(laBikeNr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(laBikeNrValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(laDistanceValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(laMaxSpeedValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(laAvgSpeedValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(laAvgCadenceValue, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(laMaxCadenceValue, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
        );
        pLeftLayout.setVerticalGroup(
            pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLeftLayout.createSequentialGroup()
                .addComponent(laSpeedData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pLeftLayout.createSequentialGroup()
                        .addComponent(laAvgSpeed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laMaxSpeed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laDistance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laBikeNr))
                    .addGroup(pLeftLayout.createSequentialGroup()
                        .addComponent(laAvgSpeedValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laMaxSpeedValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laDistanceValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laBikeNrValue)))
                .addGap(25, 25, 25)
                .addComponent(laCadenceData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pLeftLayout.createSequentialGroup()
                        .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(laAvgCadence)
                            .addComponent(laAvgCadenceValue))
                        .addGap(21, 21, 21))
                    .addGroup(pLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(laMaxCadence)
                        .addComponent(laMaxCadenceValue)))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        add(pLeft);

        laAltitudeData.setFont(laAltitudeData.getFont().deriveFont(laAltitudeData.getFont().getStyle() | java.awt.Font.BOLD));
        laAltitudeData.setText("_Altitude Data");
        laAltitudeData.setName("pv.opt.altitude_data"); // NOI18N

        laMinAltitude.setText("_Minimum:");
        laMinAltitude.setName("pv.opt.minimum"); // NOI18N

        laAvgAltitude.setText("_Average:");
        laAvgAltitude.setName("pv.opt.average"); // NOI18N

        laMaxAltitude.setText("_Maximum");
        laMaxAltitude.setName("pv.opt.maximum"); // NOI18N

        laAscent.setText("_Ascent:");
        laAscent.setName("pv.opt.ascent"); // NOI18N

        laTemperatureData.setFont(laTemperatureData.getFont().deriveFont(laTemperatureData.getFont().getStyle() | java.awt.Font.BOLD));
        laTemperatureData.setText("_Temperature Data");
        laTemperatureData.setName("pv.opt.temperature_data"); // NOI18N

        laMinTemperature.setText("_Minimum:");
        laMinTemperature.setName("pv.opt.minimum"); // NOI18N

        laAvgTemperature.setText("_Average:");
        laAvgTemperature.setName("pv.opt.average"); // NOI18N

        laMaxTemperature.setText("_Maximum:");
        laMaxTemperature.setName("pv.opt.maximum"); // NOI18N

        laMinAltitudeValue.setText("_n.a.");

        laAvgAltitudeValue.setText("_n.a.");

        laMaxAltitudeValue.setText("_n.a.");

        laAscentValue.setText("_n.a.");

        laMinTemperatureValue.setText("_n.a.");

        laAvgTemperatureValue.setText("_n.a.");

        laMaxTemperatureValue.setText("_n.a.");

        javax.swing.GroupLayout pRightLayout = new javax.swing.GroupLayout(pRight);
        pRight.setLayout(pRightLayout);
        pRightLayout.setHorizontalGroup(
            pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRightLayout.createSequentialGroup()
                .addGroup(pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laTemperatureData)
                    .addGroup(pRightLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(laMinTemperature)
                            .addComponent(laAvgTemperature)
                            .addComponent(laMaxTemperature)
                            .addComponent(laMinAltitude)
                            .addComponent(laAvgAltitude)
                            .addComponent(laMaxAltitude)
                            .addComponent(laAscent))
                        .addGap(7, 7, 7)
                        .addGroup(pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(laMinAltitudeValue, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(laAvgAltitudeValue, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(laMaxAltitudeValue, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(laAscentValue, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(laMinTemperatureValue, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(laAvgTemperatureValue, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(laMaxTemperatureValue, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                    .addComponent(laAltitudeData))
                .addContainerGap())
        );
        pRightLayout.setVerticalGroup(
            pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRightLayout.createSequentialGroup()
                .addComponent(laAltitudeData, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laMinAltitude)
                    .addComponent(laMinAltitudeValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laAvgAltitude)
                    .addComponent(laAvgAltitudeValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laMaxAltitude)
                    .addComponent(laMaxAltitudeValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laAscent)
                    .addComponent(laAscentValue))
                .addGap(25, 25, 25)
                .addComponent(laTemperatureData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laMinTemperature)
                    .addComponent(laMinTemperatureValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laAvgTemperature)
                    .addComponent(laAvgTemperatureValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laMaxTemperature)
                    .addComponent(laMaxTemperatureValue))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        add(pRight);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel laAltitudeData;
    private javax.swing.JLabel laAscent;
    private javax.swing.JLabel laAscentValue;
    private javax.swing.JLabel laAvgAltitude;
    private javax.swing.JLabel laAvgAltitudeValue;
    private javax.swing.JLabel laAvgCadence;
    private javax.swing.JLabel laAvgCadenceValue;
    private javax.swing.JLabel laAvgSpeed;
    private javax.swing.JLabel laAvgSpeedValue;
    private javax.swing.JLabel laAvgTemperature;
    private javax.swing.JLabel laAvgTemperatureValue;
    private javax.swing.JLabel laBikeNr;
    private javax.swing.JLabel laBikeNrValue;
    private javax.swing.JLabel laCadenceData;
    private javax.swing.JLabel laDistance;
    private javax.swing.JLabel laDistanceValue;
    private javax.swing.JLabel laMaxAltitude;
    private javax.swing.JLabel laMaxAltitudeValue;
    private javax.swing.JLabel laMaxCadence;
    private javax.swing.JLabel laMaxCadenceValue;
    private javax.swing.JLabel laMaxSpeed;
    private javax.swing.JLabel laMaxSpeedValue;
    private javax.swing.JLabel laMaxTemperature;
    private javax.swing.JLabel laMaxTemperatureValue;
    private javax.swing.JLabel laMinAltitude;
    private javax.swing.JLabel laMinAltitudeValue;
    private javax.swing.JLabel laMinTemperature;
    private javax.swing.JLabel laMinTemperatureValue;
    private javax.swing.JLabel laSpeedData;
    private javax.swing.JLabel laTemperatureData;
    private javax.swing.JPanel pLeft;
    private javax.swing.JPanel pRight;
    // End of variables declaration//GEN-END:variables
    
}
